#!/bin/sh

# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed.

dmenu -w 350 -x 550 -y 360 -fn SF\\Compact\\Text-10:Bold -P -p " $1" <&- && echo
