#!/bin/bash
xrdb -merge ~/.Xresources                                 
sed -i "/selected-active-background:/ cselected-active-background: $(xrdb -query | grep '.color12:' | awk '{print $NF}');" $HOME/.config/rofi/themes-rofi.rasi 
